  function initSolarSystem() {
      // ═══════════════════════════════════════════════════════════════════
      //  PLANET DATA
      // ═══════════════════════════════════════════════════════════════════
      const PLANET_DATA = [
        {
          name: 'Mercury',
          subtitle: 'Innermost rocky world',
          color: 0x9e9e9e,
          emissive: 0x222222,
          radius: 0.38,
          orbitRadius: 8,
          orbitSpeed: 4.74,
          rotationSpeed: 0.003,
          tilt: 0.034,
          navColor: '#9e9e9e',
          texture: null,
          facts: [
            { icon: '🌑', text: 'Orbits the Sun in just 88 Earth days — the fastest of all planets — yet a single day lasts 59 Earth days.' },
            { icon: '🌡️', text: 'Temperatures swing wildly: 430 °C on the sunlit side, plummeting to −180 °C at night, because it has no atmosphere to retain heat.' },
            { icon: '📏', text: 'Smaller than some moons, with a radius of only 2,440 km — just 38% of Earth\'s.' },
            { icon: '🔭', text: 'Its massive iron core makes up 85% of its radius, giving Mercury a surprisingly strong magnetic field for its size.' },
            { icon: '💡', text: 'Ice exists in permanently shadowed craters at Mercury\'s poles, despite being the closest planet to the Sun.' },
          ]
        },
        {
          name: 'Venus',
          subtitle: 'Earth\'s volcanic twin',
          color: 0xe8b86d,
          emissive: 0x3a2800,
          radius: 0.95,
          orbitRadius: 12,
          orbitSpeed: 3.5,
          rotationSpeed: -0.001,   // retrograde rotation
          tilt: 177.4 * Math.PI / 180,
          navColor: '#e8b86d',
          facts: [
            { icon: '🌡️', text: 'The hottest planet at 465 °C average — hotter than Mercury — thanks to a runaway greenhouse effect driven by a thick CO₂ atmosphere.' },
            { icon: '🔄', text: 'Spins backwards (east to west) and so slowly that a Venusian day (243 Earth days) is longer than its year (225 Earth days).' },
            { icon: '☁️', text: 'Clouds of sulfuric acid blanket the planet, making its surface invisible to ordinary cameras.' },
            { icon: '🌋', text: 'Home to over 1,600 major volcanoes — more than any other body in the solar system.' },
            { icon: '💡', text: 'Pressure at Venus\'s surface is 90 times that of Earth — equivalent to being 900 m underwater.' },
          ]
        },
        {
          name: 'Earth',
          subtitle: 'Our pale blue dot',
          color: 0x2e86ab,
          emissive: 0x001a22,
          radius: 1.0,
          orbitRadius: 16,
          orbitSpeed: 2.98,
          rotationSpeed: 0.01,
          tilt: 23.5 * Math.PI / 180,
          navColor: '#2e86ab',
          facts: [
            { icon: '🌊', text: '71% of Earth\'s surface is covered by liquid water — the only confirmed planet where this occurs, making life possible.' },
            { icon: '🌍', text: 'Earth\'s axis tilts 23.5°, creating our four seasons and stabilised by the Moon\'s gravitational influence.' },
            { icon: '🛡️', text: 'The magnetic field generated by Earth\'s liquid iron core deflects deadly solar wind, protecting all life on the surface.' },
            { icon: '🌑', text: 'Our Moon is unusually large relative to Earth (1/4 its size), likely formed from a Mars-sized collision 4.5 billion years ago.' },
            { icon: '💡', text: 'Earth is the densest planet in the solar system, at 5.51 g/cm³, due to its large iron-nickel core.' },
          ]
        },
        {
          name: 'Mars',
          subtitle: 'The red planet',
          color: 0xc1440e,
          emissive: 0x2a0800,
          radius: 0.53,
          orbitRadius: 21,
          orbitSpeed: 2.41,
          rotationSpeed: 0.009,
          tilt: 25.2 * Math.PI / 180,
          navColor: '#c1440e',
          facts: [
            { icon: '🏔️', text: 'Olympus Mons is the tallest volcano in the solar system at 21.9 km — nearly three times the height of Everest.' },
            { icon: '🌡️', text: 'Temperatures average −60 °C but can reach 20 °C at the equator in summer and drop to −125 °C at the poles.' },
            { icon: '🔴', text: 'Its red colour comes from iron oxide (rust) in the soil, while dust storms can envelop the entire planet for months.' },
            { icon: '🌀', text: 'A Martian day (sol) is just 24 hours 37 minutes — almost identical to Earth\'s — making it the most hospitable-rhythmed planet.' },
            { icon: '💡', text: 'Mars has two tiny moons (Phobos and Deimos) likely captured asteroids, and Phobos is slowly spiralling inward — it will crash or break up in ~50 million years.' },
          ]
        },
        {
          name: 'Jupiter',
          subtitle: 'King of planets',
          color: 0xc88b3a,
          emissive: 0x1a0a00,
          radius: 2.6,
          orbitRadius: 30,
          orbitSpeed: 1.31,
          rotationSpeed: 0.022,
          tilt: 3.1 * Math.PI / 180,
          navColor: '#c88b3a',
          hasStripes: true,
          facts: [
            { icon: '🪐', text: 'More than 1,300 Earths would fit inside Jupiter, and its mass is 2.5× greater than all other planets combined.' },
            { icon: '🌀', text: 'The Great Red Spot is a storm larger than Earth that has been raging for at least 350 years, though it is slowly shrinking.' },
            { icon: '⚡', text: 'Jupiter emits more heat than it receives from the Sun — its interior is still slowly contracting, releasing gravitational energy.' },
            { icon: '🌙', text: 'Has 95 known moons. Ganymede, the largest, is bigger than Mercury and has its own magnetic field.' },
            { icon: '💡', text: 'Jupiter acts as a gravitational "shield," deflecting many comets and asteroids that would otherwise strike Earth.' },
          ]
        },
        {
          name: 'Saturn',
          subtitle: 'Lord of the rings',
          color: 0xe4d191,
          emissive: 0x1a1400,
          radius: 2.2,
          orbitRadius: 40,
          orbitSpeed: 0.97,
          rotationSpeed: 0.02,
          tilt: 26.7 * Math.PI / 180,
          navColor: '#e4d191',
          hasRings: true,
          facts: [
            { icon: '💍', text: 'Saturn\'s rings span 282,000 km but are only 10–100 m thick — they\'re made of ice chunks ranging from dust to house-sized boulders.' },
            { icon: '⚖️', text: 'The least dense planet — less dense than water. If you could find an ocean large enough, Saturn would float.' },
            { icon: '🌀', text: 'A hexagonal storm pattern sits at Saturn\'s north pole, stretching wider than Earth, stable for decades.' },
            { icon: '🌙', text: 'Titan, its largest moon, has a thick nitrogen atmosphere and lakes of liquid methane — the only moon with a dense atmosphere.' },
            { icon: '💡', text: 'Saturn\'s rings are young (100–200 million years old) and will disappear within 300 million years as they rain into Saturn.' },
          ]
        },
        {
          name: 'Uranus',
          subtitle: 'The tilted ice giant',
          color: 0x7de8e8,
          emissive: 0x003333,
          radius: 1.6,
          orbitRadius: 50,
          orbitSpeed: 0.68,
          rotationSpeed: -0.013,  // retrograde
          tilt: 97.8 * Math.PI / 180,
          navColor: '#7de8e8',
          hasRings: true,
          facts: [
            { icon: '🔄', text: 'Uranus rotates on its side — axial tilt of 97.8° — so each pole gets 42 years of continuous sunlight then 42 years of darkness.' },
            { icon: '❄️', text: 'An "ice giant" with a mantle of water, methane, and ammonia ice under crushing pressure around a small rocky core.' },
            { icon: '🌡️', text: 'Despite not being the farthest planet, Uranus holds the record for the coldest planetary atmosphere at −224 °C.' },
            { icon: '💍', text: 'Has 13 known rings, oriented nearly vertically due to its extreme tilt — they were only discovered in 1977.' },
            { icon: '💡', text: 'Scientists believe a massive collision billions of years ago knocked Uranus onto its side, permanently changing its seasons.' },
          ]
        },
        {
          name: 'Neptune',
          subtitle: 'The windiest world',
          color: 0x3f54ba,
          emissive: 0x000820,
          radius: 1.55,
          orbitRadius: 60,
          orbitSpeed: 0.54,
          rotationSpeed: 0.014,
          tilt: 28.3 * Math.PI / 180,
          navColor: '#3f54ba',
          hasRings: true,
          facts: [
            { icon: '🌬️', text: 'Wind speeds reach 2,100 km/h — the fastest in the solar system — despite being the farthest planet and coldest at −200 °C.' },
            { icon: '🔭', text: 'Discovered by mathematics: Le Verrier predicted its position from gravitational anomalies in Uranus\'s orbit before it was seen (1846).' },
            { icon: '🌊', text: 'One Neptune year equals 165 Earth years — it completed its first full orbit since discovery only in 2011.' },
            { icon: '🌙', text: 'Its moon Triton orbits backwards (retrograde) and is geologically active, shooting nitrogen geysers — likely a captured Kuiper Belt object.' },
            { icon: '💡', text: 'Diamond rain may occur in Neptune\'s interior, where extreme pressure converts methane carbon into diamond crystals.' },
          ]
        }
      ];

      // ═══════════════════════════════════════════════════════════════════
      //  SCENE SETUP
      // ═══════════════════════════════════════════════════════════════════
      const container   = document.getElementById('canvas-container');
      const renderer    = new THREE.WebGLRenderer({ antialias: true, alpha: false });
      renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
      renderer.setSize(window.innerWidth, window.innerHeight);
      container.appendChild(renderer.domElement);

      const scene  = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.1, 2000);
      camera.position.set(0, 45, 80);
      camera.lookAt(0, 0, 0);

      // ─── Lighting ────────────────────────────────────────────────────
      // Strong point light from the sun position — no decay limit (0 = infinite)
      const sunLight = new THREE.PointLight(0xfff5e0, 3.0, 0);
      sunLight.position.set(0, 0, 0);
      scene.add(sunLight);

      // Generous ambient so texture colours are visible even on the dark side
      const ambient = new THREE.AmbientLight(0xffffff, 0.5);
      scene.add(ambient);

      // ─── Procedural starfield ─────────────────────────────────────────
      (function createStarfield() {
        const count = 7000;
        const geo   = new THREE.BufferGeometry();
        const pos   = new Float32Array(count * 3);
        for (let i = 0; i < count; i++) {
          const r   = 500 + Math.random() * 600;
          const th  = Math.random() * Math.PI * 2;
          const ph  = Math.acos(2 * Math.random() - 1);
          pos[i*3]   = r * Math.sin(ph) * Math.cos(th);
          pos[i*3+1] = r * Math.sin(ph) * Math.sin(th);
          pos[i*3+2] = r * Math.cos(ph);
        }
        geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
        scene.add(new THREE.Points(geo,
          new THREE.PointsMaterial({ color: 0xffffff, size: 0.55, sizeAttenuation: true, transparent: true, opacity: 0.9 })
        ));
      })();

      // ═══════════════════════════════════════════════════════════════════
      //  SUN
      // ═══════════════════════════════════════════════════════════════════
      function createSun() {
        // Core — MeshBasicMaterial is unaffected by lights, always fully bright
        const sun = new THREE.Mesh(
          new THREE.SphereGeometry(3.5, 64, 64),
          new THREE.MeshBasicMaterial({ color: 0xffcc33 })
        );
        scene.add(sun);

        // Layered corona glows
        [{ r: 4.4, c: 0xff8800, o: 0.14 },
        { r: 5.6, c: 0xffaa00, o: 0.07 },
        { r: 7.0, c: 0xff6600, o: 0.03 }].forEach(({ r, c, o }) => {
          scene.add(new THREE.Mesh(
            new THREE.SphereGeometry(r, 32, 32),
            new THREE.MeshBasicMaterial({ color: c, transparent: true, opacity: o, side: THREE.BackSide })
          ));
        });

        return sun;
      }
      const sunMesh = createSun();

      // ═══════════════════════════════════════════════════════════════════
      //  ORBIT LINES
      // ═══════════════════════════════════════════════════════════════════
      function createOrbit(radius) {
        const pts = [];
        for (let i = 0; i <= 128; i++) {
          const a = (i / 128) * Math.PI * 2;
          pts.push(new THREE.Vector3(Math.cos(a) * radius, 0, Math.sin(a) * radius));
        }
        return new THREE.Line(
          new THREE.BufferGeometry().setFromPoints(pts),
          new THREE.LineBasicMaterial({ color: 0x334466, transparent: true, opacity: 0.35 })
        );
      }

      // ═══════════════════════════════════════════════════════════════════
      //  PLANET MESH BUILDER  (fully procedural — no external textures)
      // ═══════════════════════════════════════════════════════════════════
      const PLANET_CFG = {
        Mercury: { color: 0xb5b5b5, emissive: 0x1a1a1a, shininess: 12,  specular: 0x333333 },
        Venus:   { color: 0xe8c97a, emissive: 0x2a1a00, shininess: 40,  specular: 0x664400 },
        Earth:   { color: 0x2a6ab5, emissive: 0x001122, shininess: 45,  specular: 0x224488 },
        Mars:    { color: 0xc1440e, emissive: 0x1a0400, shininess: 12,  specular: 0x331100 },
        Jupiter: { color: 0xc88b3a, emissive: 0x0f0800, shininess: 8,   specular: 0x221100 },
        Saturn:  { color: 0xe4d191, emissive: 0x141000, shininess: 8,   specular: 0x221a00 },
        Uranus:  { color: 0x7de8e8, emissive: 0x002222, shininess: 20,  specular: 0x004444 },
        Neptune: { color: 0x3f54ba, emissive: 0x000822, shininess: 20,  specular: 0x001144 },
      };

      function buildPlanetMesh(data) {
        const group = new THREE.Group();
        const cfg   = PLANET_CFG[data.name];

        const sphere = new THREE.Mesh(
          new THREE.SphereGeometry(data.radius, 64, 64),
          new THREE.MeshPhongMaterial({
            color:     cfg.color,
            emissive:  new THREE.Color(cfg.emissive),
            specular:  new THREE.Color(cfg.specular),
            shininess: cfg.shininess,
          })
        );
        sphere.rotation.z = data.tilt;
        group.add(sphere);

        // ── Earth: green continents overlay + atmosphere ──────────────
        if (data.name === 'Earth') {
          // Continent-like second layer with partial coverage (dodecahedron noise trick)
          const landSphere = new THREE.Mesh(
            new THREE.SphereGeometry(data.radius * 1.001, 64, 64),
            new THREE.MeshPhongMaterial({
              color:       0x2d6e2d,
              emissive:    new THREE.Color(0x001100),
              transparent: true,
              opacity:     0.45,
              shininess:   5,
            })
          );
          landSphere.rotation.y = 1.2;
          landSphere.rotation.z = data.tilt;
          group.add(landSphere);

          // Atmosphere glow
          group.add(new THREE.Mesh(
            new THREE.SphereGeometry(data.radius * 1.07, 32, 32),
            new THREE.MeshBasicMaterial({ color: 0x4499ff, transparent: true, opacity: 0.10, side: THREE.BackSide })
          ));
        }

        // ── Venus: thick atmosphere glow ─────────────────────────────
        if (data.name === 'Venus') {
          group.add(new THREE.Mesh(
            new THREE.SphereGeometry(data.radius * 1.06, 32, 32),
            new THREE.MeshBasicMaterial({ color: 0xd4933a, transparent: true, opacity: 0.12, side: THREE.BackSide })
          ));
        }

        // ── Jupiter: visible cloud bands ─────────────────────────────
        if (data.name === 'Jupiter') {
          const bands = [
            { y: 0.55, color: 0xc07028, w: 0.09 },
            { y: 0.28, color: 0xe8c090, w: 0.08 },
            { y: 0.0,  color: 0xb87030, w: 0.12 },
            { y:-0.28, color: 0xd8a060, w: 0.09 },
            { y:-0.55, color: 0xc07028, w: 0.08 },
          ];
          bands.forEach(b => {
            const ring = new THREE.Mesh(
              new THREE.TorusGeometry(data.radius * 1.002, data.radius * b.w, 4, 80),
              new THREE.MeshBasicMaterial({ color: b.color, transparent: true, opacity: 0.35 })
            );
            ring.rotation.x = Math.PI / 2;
            ring.position.y = b.y * data.radius;
            group.add(ring);
          });
          // Great Red Spot
          const spot = new THREE.Mesh(
            new THREE.SphereGeometry(data.radius * 0.18, 16, 16),
            new THREE.MeshBasicMaterial({ color: 0xaa2200, transparent: true, opacity: 0.55 })
          );
          spot.position.set(data.radius * 0.92, -data.radius * 0.2, data.radius * 0.3);
          group.add(spot);
        }

        // ── Saturn: rings ────────────────────────────────────────────
        if (data.name === 'Saturn') {
          [{ i: 1.25, o: 1.6,  c: 0xd8c88a, op: 0.70 },
          { i: 1.65, o: 1.95, c: 0xc4b070, op: 0.55 },
          { i: 2.0,  o: 2.35, c: 0xb8a060, op: 0.40 }].forEach(r => {
            const ring = new THREE.Mesh(
              new THREE.RingGeometry(data.radius * r.i, data.radius * r.o, 80),
              new THREE.MeshBasicMaterial({ color: r.c, side: THREE.DoubleSide, transparent: true, opacity: r.op })
            );
            ring.rotation.x = Math.PI / 2;
            group.add(ring);
          });
          // Ring group tilt
          const rg = group.children.filter(c => c.geometry && c.geometry.type === 'RingGeometry');
          const tiltG = new THREE.Group();
          rg.forEach(r => { group.remove(r); tiltG.add(r); });
          tiltG.rotation.z = data.tilt;
          group.add(tiltG);
        }

        // ── Uranus / Neptune: thin rings ─────────────────────────────
        if (data.name === 'Uranus' || data.name === 'Neptune') {
          const inner = data.name === 'Uranus' ? 1.5 : 1.45;
          const outer = data.name === 'Uranus' ? 1.9 : 1.72;
          const color = data.name === 'Uranus' ? 0x88eeff : 0x3355aa;
          const ringG = new THREE.Group();
          const ring  = new THREE.Mesh(
            new THREE.RingGeometry(data.radius * inner, data.radius * outer, 96),
            new THREE.MeshBasicMaterial({ color, side: THREE.DoubleSide, transparent: true, opacity: 0.22 })
          );
          ring.rotation.x = Math.PI / 2;
          ringG.add(ring);
          ringG.rotation.z = data.tilt;
          group.add(ringG);
        }

        // ── Ice giant atmosphere ──────────────────────────────────────
        if (data.name === 'Uranus' || data.name === 'Neptune') {
          const c = data.name === 'Neptune' ? 0x2255cc : 0x44cccc;
          group.add(new THREE.Mesh(
            new THREE.SphereGeometry(data.radius * 1.05, 32, 32),
            new THREE.MeshBasicMaterial({ color: c, transparent: true, opacity: 0.09, side: THREE.BackSide })
          ));
        }

        return { group, sphere };
      }

      // ═══════════════════════════════════════════════════════════════════
      //  BUILD ALL PLANETS
      // ═══════════════════════════════════════════════════════════════════
      const planets = []; // { data, group, sphere, orbitAngle, pivot }

      PLANET_DATA.forEach((data, idx) => {
        scene.add(createOrbit(data.orbitRadius));

        const pivot = new THREE.Group();
        scene.add(pivot);

        const { group, sphere } = buildPlanetMesh(data);

        // Start at evenly spread angles
        const startAngle = (idx / PLANET_DATA.length) * Math.PI * 2;
        group.position.x = Math.cos(startAngle) * data.orbitRadius;
        group.position.z = Math.sin(startAngle) * data.orbitRadius;

        pivot.add(group);

        planets.push({ data, group, sphere, orbitAngle: startAngle, pivot });
      });

      // ═══════════════════════════════════════════════════════════════════
      //  SUN DATA  (for the info panel)
      // ═══════════════════════════════════════════════════════════════════
      const SUN_DATA = {
        name:     'The Sun',
        subtitle: 'Our star · Heart of the solar system',
        navColor: '#ffcc33',
        facts: [
          { icon: '⭐', text: 'The Sun contains 99.86% of all the mass in the solar system — over 1.3 million Earths would fit inside it.' },
          { icon: '🌡️', text: 'Its core reaches 15 million °C, where hydrogen nuclei fuse into helium, releasing the energy that powers all life on Earth.' },
          { icon: '💡', text: 'Light from the Sun takes ~8 minutes 20 seconds to reach Earth, yet that same energy spent up to 100,000 years travelling from the core to the surface.' },
          { icon: '🌀', text: 'The Sun rotates once every 25 days at its equator but 35 days near its poles — it is not a solid body, so different latitudes spin at different speeds.' },
          { icon: '🔭', text: 'Currently a middle-aged yellow dwarf (G-type star), the Sun will exhaust its hydrogen in ~5 billion years, expand into a red giant, and likely engulf Mercury, Venus, and possibly Earth.' },
        ],
      };

      // ═══════════════════════════════════════════════════════════════════
      //  PLANET NAV  (Sun first, then all eight planets)
      // ═══════════════════════════════════════════════════════════════════
      const navEl = document.getElementById('planet-nav');

      // Sun button at the top of the list
      const sunNavBtn = document.createElement('button');
      sunNavBtn.className = 'nav-btn';
      sunNavBtn.id = 'nav-sun';
      sunNavBtn.style.setProperty('--planet-color', SUN_DATA.navColor);
      sunNavBtn.innerHTML = `
        <span class="nav-label">${SUN_DATA.name}</span>
        <span class="nav-dot" style="background:${SUN_DATA.navColor}; box-shadow:0 0 6px ${SUN_DATA.navColor}"></span>
      `;
      sunNavBtn.addEventListener('click', () => selectSun());
      navEl.appendChild(sunNavBtn);

      // Planet buttons
      planets.forEach((planet, i) => {
        const btn = document.createElement('button');
        btn.className = 'nav-btn';
        btn.dataset.index = i;
        btn.style.setProperty('--planet-color', planet.data.navColor);
        btn.innerHTML = `
          <span class="nav-label">${planet.data.name}</span>
          <span class="nav-dot" style="background:${planet.data.navColor}"></span>
        `;
        btn.addEventListener('click', () => selectPlanet(i));
        navEl.appendChild(btn);
      });

      // ═══════════════════════════════════════════════════════════════════
      //  CAMERA STATE  — pure spherical orbit around a focus point
      //  The camera always sits at (theta, phi, radius) relative to `focus`.
      //  Selecting a planet changes focus + radius; user drag/scroll always
      //  works on top of whatever state we're in.
      // ═══════════════════════════════════════════════════════════════════
      let selectedIndex  = -1;
      let orbitSpeedMult = 1.0;

      // Current (rendered) camera spherical coords
      let camTheta  = 0.4;
      let camPhi    = 0.55;
      let camRadius = 90;

      // Targets we lerp toward
      let tgtTheta  = camTheta;
      let tgtPhi    = camPhi;
      let tgtRadius = camRadius;

      // The point in world-space the camera orbits around (lerped each frame)
      const focus    = new THREE.Vector3(0, 0, 0);
      const tgtFocus = new THREE.Vector3(0, 0, 0);

      // Zoom limits (absolute distance from focus)
      const MIN_ZOOM = 4;
      const MAX_ZOOM = 220;

      // Drag state
      let isDragging   = false;
      let dragStart    = { x: 0, y: 0 };
      let dragMoved    = false;   // distinguishes click vs drag

      const raycaster = new THREE.Raycaster();
      const mouse     = new THREE.Vector2();
      const tooltip   = document.getElementById('tooltip');
      let hoveredIdx  = -1;

      // ─── Info panel refs ─────────────────────────────────────────────
      const infoPanel  = document.getElementById('info-panel');
      const panelClose = document.getElementById('panel-close');
      const panelTitle = document.getElementById('panel-title');
      const panelSub   = document.getElementById('panel-subtitle');
      const panelFacts = document.getElementById('panel-facts');
      const panelEye   = document.getElementById('panel-eyebrow');

      panelClose.addEventListener('click', () => {
        selectedIndex = -1;
        isSunSelected = false;
        infoPanel.classList.remove('visible');
        document.querySelectorAll('.nav-btn').forEach(b => b.classList.remove('active'));
        // Return to overview: focus on sun, pull back
        tgtFocus.set(0, 0, 0);
        tgtPhi    = 0.55;
        tgtRadius = 90;
      });

      // ─── Select the Sun ──────────────────────────────────────────────
      let isSunSelected = false;

      function selectSun() {
        selectedIndex = -1;   // sun is not a planet
        isSunSelected = true;

        // Highlight only the sun nav button
        document.querySelectorAll('.nav-btn').forEach(b => b.classList.remove('active'));
        document.getElementById('nav-sun').classList.add('active');

        // Populate info panel with sun data
        panelEye.textContent   = 'Our Star';
        panelTitle.textContent = SUN_DATA.name;
        panelSub.textContent   = SUN_DATA.subtitle;
        panelFacts.innerHTML   = SUN_DATA.facts.map(f =>
          `<div class="fact-item">
            <span class="fact-icon">${f.icon}</span>
            <p class="fact-text">${f.text}</p>
          </div>`
        ).join('');
        infoPanel.classList.add('visible');

        // Zoom toward the sun at the origin
        tgtFocus.set(0, 0, 0);
        tgtRadius = 18;
        tgtPhi    = 0.35;
      }

      // ─── Select a planet ─────────────────────────────────────────────
      function selectPlanet(idx) {
        selectedIndex = idx;
        isSunSelected = false;   // release sun lock so focus can chase the planet
        const p = planets[idx];

        document.querySelectorAll('.nav-btn').forEach((b, i) => b.classList.toggle('active', i === idx));
        document.getElementById('nav-sun').classList.remove('active');

        panelEye.textContent   = `Planet ${idx + 1} of 8`;
        panelTitle.textContent = p.data.name;
        panelSub.textContent   = p.data.subtitle;
        panelFacts.innerHTML   = p.data.facts.map(f =>
          `<div class="fact-item">
            <span class="fact-icon">${f.icon}</span>
            <p class="fact-text">${f.text}</p>
          </div>`
        ).join('');
        infoPanel.classList.add('visible');

        // Aim focus at the planet's current position; zoom to a comfortable distance
        const wp = new THREE.Vector3();
        p.group.getWorldPosition(wp);
        tgtFocus.copy(wp);
        tgtRadius = p.data.radius * 7 + 10;
        tgtPhi    = 0.35;
      }

      // ═══════════════════════════════════════════════════════════════════
      //  MOUSE / TOUCH EVENTS
      // ═══════════════════════════════════════════════════════════════════

      // ── Mouse down ───────────────────────────────────────────────────
      renderer.domElement.addEventListener('mousedown', e => {
        isDragging = true;
        dragMoved  = false;
        dragStart  = { x: e.clientX, y: e.clientY };
        renderer.domElement.style.cursor = 'grabbing';
      });

      // ── Mouse up / click ─────────────────────────────────────────────
      renderer.domElement.addEventListener('mouseup', e => {
        isDragging = false;
        renderer.domElement.style.cursor = hoveredIdx >= 0 ? 'pointer' : 'grab';
        if (!dragMoved) handleClick(e);   // only fire click if mouse didn't move
      });

      // ── Mouse move ───────────────────────────────────────────────────
      renderer.domElement.addEventListener('mousemove', e => {
        if (isDragging) {
          const dx = e.clientX - dragStart.x;
          const dy = e.clientY - dragStart.y;
          if (Math.abs(dx) > 2 || Math.abs(dy) > 2) dragMoved = true;

          // Rotate around focus — sensitivity scales with distance so far-out feels natural
          const sensitivity = 0.003;
          tgtTheta -= dx * sensitivity;
          tgtPhi    = Math.max(0.05, Math.min(Math.PI / 2 - 0.05, tgtPhi + dy * sensitivity));
          dragStart = { x: e.clientX, y: e.clientY };
          return;
        }

        // Hover detection — planets + sun
        mouse.x = ( e.clientX / window.innerWidth)  * 2 - 1;
        mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
        raycaster.setFromCamera(mouse, camera);
        const planetHits = raycaster.intersectObjects(planets.map(p => p.sphere));
        const sunHits    = raycaster.intersectObject(sunMesh);
        if (planetHits.length > 0) {
          const hi = planets.findIndex(p => p.sphere === planetHits[0].object);
          hoveredIdx = hi;
          tooltip.textContent = planets[hi].data.name;
          tooltip.style.left  = (e.clientX + 14) + 'px';
          tooltip.style.top   = (e.clientY - 28) + 'px';
          tooltip.classList.add('visible');
          renderer.domElement.style.cursor = 'pointer';
        } else if (sunHits.length > 0) {
          hoveredIdx = -1;
          tooltip.textContent = 'The Sun';
          tooltip.style.left  = (e.clientX + 14) + 'px';
          tooltip.style.top   = (e.clientY - 28) + 'px';
          tooltip.classList.add('visible');
          renderer.domElement.style.cursor = 'pointer';
        } else {
          hoveredIdx = -1;
          tooltip.classList.remove('visible');
          renderer.domElement.style.cursor = 'grab';
        }
      });

      renderer.domElement.addEventListener('mouseleave', () => {
        isDragging = false;
        hoveredIdx = -1;
        tooltip.classList.remove('visible');
      });

      // ── Scroll / wheel zoom ──────────────────────────────────────────
      renderer.domElement.addEventListener('wheel', e => {
        e.preventDefault();
        // Logarithmic feel: zoom faster when far, slower when close
        const zoomSpeed = tgtRadius * 0.001;
        tgtRadius = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, tgtRadius + e.deltaY * zoomSpeed * 8));
      }, { passive: false });

      // ── Touch ────────────────────────────────────────────────────────
      let lastTouchDist = 0;
      let lastTouchMid  = { x: 0, y: 0 };

      renderer.domElement.addEventListener('touchstart', e => {
        if (e.touches.length === 1) {
          isDragging = true;
          dragMoved  = false;
          dragStart  = { x: e.touches[0].clientX, y: e.touches[0].clientY };
        } else if (e.touches.length === 2) {
          isDragging    = false;
          lastTouchDist = Math.hypot(
            e.touches[0].clientX - e.touches[1].clientX,
            e.touches[0].clientY - e.touches[1].clientY
          );
        }
      }, { passive: true });

      renderer.domElement.addEventListener('touchmove', e => {
        e.preventDefault();
        if (e.touches.length === 1 && isDragging) {
          const dx = e.touches[0].clientX - dragStart.x;
          const dy = e.touches[0].clientY - dragStart.y;
          if (Math.abs(dx) > 2 || Math.abs(dy) > 2) dragMoved = true;
          tgtTheta -= dx * 0.004;
          tgtPhi    = Math.max(0.05, Math.min(Math.PI / 2 - 0.05, tgtPhi + dy * 0.004));
          dragStart = { x: e.touches[0].clientX, y: e.touches[0].clientY };
        } else if (e.touches.length === 2) {
          const dist = Math.hypot(
            e.touches[0].clientX - e.touches[1].clientX,
            e.touches[0].clientY - e.touches[1].clientY
          );
          const delta = lastTouchDist - dist;
          tgtRadius   = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, tgtRadius + delta * 0.25));
          lastTouchDist = dist;
        }
      }, { passive: false });

      renderer.domElement.addEventListener('touchend', e => {
        if (e.touches.length === 0) {
          isDragging = false;
          if (!dragMoved && e.changedTouches.length === 1) {
            const t = e.changedTouches[0];
            handleClick({ clientX: t.clientX, clientY: t.clientY });
          }
        }
      });

      // ── Click to select ──────────────────────────────────────────────
      function handleClick(e) {
        mouse.x = ( e.clientX / window.innerWidth)  * 2 - 1;
        mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
        raycaster.setFromCamera(mouse, camera);
        const planetHits = raycaster.intersectObjects(planets.map(p => p.sphere));
        const sunHits    = raycaster.intersectObject(sunMesh);
        if (planetHits.length > 0) {
          const idx = planets.findIndex(p => p.sphere === planetHits[0].object);
          selectPlanet(idx);
        } else if (sunHits.length > 0) {
          selectSun();
        }
      }

      // ─── Speed slider ────────────────────────────────────────────────
      document.getElementById('speed-slider').addEventListener('input', e => {
        orbitSpeedMult = parseFloat(e.target.value);
      });

      // ═══════════════════════════════════════════════════════════════════
      //  ANIMATION LOOP
      // ═══════════════════════════════════════════════════════════════════
      const clock = new THREE.Clock();

      function animate() {
        requestAnimationFrame(animate);
        const delta = clock.getDelta();

        // ── Orbit & rotate planets ───────────────────────────────────
        planets.forEach(planet => {
          planet.orbitAngle += delta * (planet.data.orbitSpeed / 50) * orbitSpeedMult;
          planet.group.position.x = Math.cos(planet.orbitAngle) * planet.data.orbitRadius;
          planet.group.position.z = Math.sin(planet.orbitAngle) * planet.data.orbitRadius;
          planet.sphere.rotation.y += planet.data.rotationSpeed * orbitSpeedMult;

          // Rotate Earth's cloud layer slightly faster than the surface
          const clouds = planet.group.getObjectByName('clouds');
          if (clouds) clouds.rotation.y += planet.data.rotationSpeed * 1.15 * orbitSpeedMult;
        });

        sunMesh.rotation.y += 0.002;

        // ── If a planet is selected, keep focus chasing it ───────────
        if (selectedIndex >= 0) {
          const wp = new THREE.Vector3();
          planets[selectedIndex].group.getWorldPosition(wp);
          tgtFocus.copy(wp);
        }
        // If sun is selected, keep focus locked on origin
        if (isSunSelected) {
          tgtFocus.set(0, 0, 0);
        }

        // ── Lerp all camera values ───────────────────────────────────
        const k = 0.08;
        camTheta  += (tgtTheta  - camTheta)  * k;
        camPhi    += (tgtPhi    - camPhi)    * k;
        camRadius += (tgtRadius - camRadius) * k;
        focus.lerp(tgtFocus, k);

        // ── Position camera in spherical coords around focus ─────────
        camera.position.set(
          focus.x + camRadius * Math.cos(camTheta) * Math.cos(camPhi),
          focus.y + camRadius * Math.sin(camPhi),
          focus.z + camRadius * Math.sin(camTheta) * Math.cos(camPhi)
        );
        camera.lookAt(focus);

        // ── Hover / selected scale ───────────────────────────────────
        planets.forEach((p, i) => {
          const t = (i === hoveredIdx || i === selectedIndex) ? 1.12 : 1.0;
          p.group.scale.lerp(new THREE.Vector3(t, t, t), 0.1);
        });
        // Sun subtle scale on hover/select
        const sunScale = (isSunSelected) ? 1.06 : 1.0;
        sunMesh.scale.lerp(new THREE.Vector3(sunScale, sunScale, sunScale), 0.08);

        renderer.render(scene, camera);
      }

      // ═══════════════════════════════════════════════════════════════════
      //  RESIZE
      // ═══════════════════════════════════════════════════════════════════
      window.addEventListener('resize', () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
      });

      // ═══════════════════════════════════════════════════════════════════
      //  BOOT  (called after Three.js is confirmed loaded)
      // ═══════════════════════════════════════════════════════════════════
        animate();
        setTimeout(() => {
          const loading = document.getElementById('loading');
          if (loading) {
            loading.classList.add('fade-out');
            setTimeout(() => loading.remove(), 700);
          }
        }, 900);
      } // end initSolarSystem()